### ISSUE TITLE
Unrecognized option "form" under "twig"

### ISSUE THREAD

**Issue by Spomky** [florianbelhomme/FlobFoundationBundle#35]
Hi,

I am facing the following issue using this bundle on Symfony 3.1: `Unrecognized option "form" under "twig"`

This error occures only when the configuration hereafter is set:
```yml
flob_foundation:
    theme:
        form: true
```
